import type { CatalogEntry, ShortcutId } from "./types";

export const SHORTCUT_CATALOG: CatalogEntry[] = [
	{
		id: "search-toggle",
		scope: "global",
		label: "Search",
		group: "App",
		remappable: true,
		defaultChord: { key: "k", mod: true },
	},
	{
		id: "map-escape",
		scope: "map",
		label: "Cancel / back",
		group: "Map",
		remappable: false,
		defaultChord: { key: "Escape" },
	},
	{
		id: "map-enter",
		scope: "map",
		label: "Finish",
		group: "Map",
		remappable: false,
		defaultChord: { key: "Enter" },
	},
	{
		id: "map-undo",
		scope: "map",
		label: "Undo",
		group: "Map",
		remappable: true,
		defaultChord: { key: "z", mod: true },
	},
	{
		id: "map-fly-to",
		scope: "map",
		label: "Fly to selection",
		group: "Map",
		remappable: true,
		defaultChord: { key: "f" },
	},
	{
		id: "map-home",
		scope: "map",
		label: "Home",
		group: "Map",
		remappable: true,
		defaultChord: { key: "h" },
	},
	{
		id: "map-isolate",
		scope: "map",
		label: "Isolate selected",
		group: "Map",
		remappable: true,
		defaultChord: { key: "i" },
	},
	{
		id: "map-exit-isolate",
		scope: "map",
		label: "Clear isolate",
		group: "Map",
		remappable: true,
		defaultChord: { key: "u" },
	},
	{
		id: "map-select-click",
		scope: "map",
		label: "Select click",
		group: "Map",
		remappable: true,
		defaultChord: { key: "1" },
	},
	{
		id: "map-select-box",
		scope: "map",
		label: "Select box",
		group: "Map",
		remappable: true,
		defaultChord: { key: "2" },
	},
	{
		id: "map-select-lasso",
		scope: "map",
		label: "Select lasso",
		group: "Map",
		remappable: true,
		defaultChord: { key: "3" },
	},
	{
		id: "map-measure-toggle",
		scope: "map",
		label: "Measure",
		group: "Map",
		remappable: true,
		defaultChord: { key: "m" },
	},
	{
		id: "map-measure-point",
		scope: "map",
		label: "Measure point",
		group: "Map",
		remappable: true,
		defaultChord: { key: "p" },
	},
	{
		id: "map-measure-length",
		scope: "map",
		label: "Measure length",
		group: "Map",
		remappable: true,
		defaultChord: { key: "l" },
	},
	{
		id: "map-measure-area",
		scope: "map",
		label: "Measure area",
		group: "Map",
		remappable: true,
		defaultChord: { key: "a" },
	},
	{
		id: "map-measure-volume",
		scope: "map",
		label: "Measure volume",
		group: "Map",
		remappable: true,
		defaultChord: { key: "v" },
	},
	{
		id: "map-comments-toggle",
		scope: "map",
		label: "Comments",
		group: "Map",
		remappable: true,
		defaultChord: { key: "c" },
	},
	{
		id: "map-edit-toggle",
		scope: "map",
		label: "Edit",
		group: "Map",
		remappable: true,
		defaultChord: { key: "Tab" },
	},
	{
		id: "map-add-geometry",
		scope: "map",
		label: "Add feature",
		group: "Map",
		remappable: true,
		defaultChord: { key: "a", mod: true },
	},
	{
		id: "map-graph-toggle",
		scope: "map",
		label: "Graph",
		group: "Map",
		remappable: true,
		defaultChord: { key: "g" },
	},
	{
		id: "map-delete",
		scope: "map",
		label: "Delete",
		group: "Map",
		remappable: true,
		defaultChord: { key: "Delete" },
		aliases: [{ key: "Backspace" }],
	},
	{
		id: "map-fly-toggle",
		scope: "map",
		label: "Fly mode",
		group: "Camera",
		remappable: true,
		defaultChord: { key: "`" },
	},
	{
		id: "tables-edit-toggle",
		scope: "tables",
		label: "Table edit",
		group: "Tables",
		remappable: true,
		defaultChord: { key: "Tab" },
	},
	{
		id: "tables-delete",
		scope: "tables",
		label: "Delete rows",
		group: "Tables",
		remappable: true,
		defaultChord: { key: "Delete" },
		aliases: [{ key: "Backspace" }],
	},
	{
		id: "fly-forward",
		scope: "map-fly",
		label: "Fly forward",
		group: "Fly",
		remappable: true,
		defaultChord: { key: "w" },
	},
	{
		id: "fly-back",
		scope: "map-fly",
		label: "Fly back",
		group: "Fly",
		remappable: true,
		defaultChord: { key: "s" },
	},
	{
		id: "fly-left",
		scope: "map-fly",
		label: "Fly left",
		group: "Fly",
		remappable: true,
		defaultChord: { key: "a" },
	},
	{
		id: "fly-right",
		scope: "map-fly",
		label: "Fly right",
		group: "Fly",
		remappable: true,
		defaultChord: { key: "d" },
	},
	{
		id: "fly-down",
		scope: "map-fly",
		label: "Fly down",
		group: "Fly",
		remappable: true,
		defaultChord: { key: "q" },
	},
	{
		id: "fly-up",
		scope: "map-fly",
		label: "Fly up",
		group: "Fly",
		remappable: true,
		defaultChord: { key: "e" },
	},
];

const BY_ID = new Map(SHORTCUT_CATALOG.map((e) => [e.id, e]));

export function catalogEntry(id: ShortcutId): CatalogEntry | undefined {
	return BY_ID.get(id);
}

export const CAMERA_SCHEMES = [
	{
		id: "globe" as const,
		label: "Globe",
		legend: "Left-drag orbit · wheel zoom · middle tilt",
	},
	{
		id: "pivot" as const,
		label: "Pivot",
		legend:
			"Middle-drag or two-finger orbit · Shift+middle pan · wheel / pinch zoom · Alt+left orbit",
	},
];
